### ISSUE TITLE
Dunglas\Heroku\Database not on autorun

### ISSUE THREAD

**Issue by brunoreis** [dunglas/api-platform-heroku#10]
When deploying I was not able to put that class on autorun. I did it locally by running composer update. But was not able to do it on heroku. 

So I decided to use this that seemed a better approach than having to rely on that Database::createParameters method: 

```
doctrine:
    dbal:
        driver: pdo_mysql
        url: "%env(DATABASE_URL)%"
```
